"""empty message

Revision ID: 1652406896c1
Revises: 419bcc77d370
Create Date: 2015-10-04 07:48:57.000282

"""

# revision identifiers, used by Alembic.
revision = '1652406896c1'
down_revision = '419bcc77d370'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
