"""empty message

Revision ID: 30ecdeaf66c9
Revises: 539a4d65265d
Create Date: 2015-10-04 07:52:06.261371

"""

# revision identifiers, used by Alembic.
revision = '30ecdeaf66c9'
down_revision = '539a4d65265d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
