"""empty message

Revision ID: 419bcc77d370
Revises: 58b7889b6803
Create Date: 2015-10-04 01:12:54.018686

"""

# revision identifiers, used by Alembic.
revision = '419bcc77d370'
down_revision = '58b7889b6803'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=20), nullable=True))
    ### end Alembic commands ###
