"""empty message

Revision ID: 59b8e255e1e6
Revises: 30ecdeaf66c9
Create Date: 2015-10-04 08:12:05.598947

"""

# revision identifiers, used by Alembic.
revision = '59b8e255e1e6'
down_revision = '30ecdeaf66c9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
