"""empty message

Revision ID: a9e97a5d7fc
Revises: 59b8e255e1e6
Create Date: 2015-10-05 07:08:22.673896

"""

# revision identifiers, used by Alembic.
revision = 'a9e97a5d7fc'
down_revision = '59b8e255e1e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referred', sa.Text(), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dpi')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters')
    ### end Alembic commands ###
