"""empty message

Revision ID: d2915b2db23d
Revises: 0d9421aedf68
Create Date: 2016-02-01 16:09:04.115412

"""

# revision identifiers, used by Alembic.
revision = 'd2915b2db23d'
down_revision = '0d9421aedf68'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('photo', sa.String(length=255), nullable=True))
    op.drop_column('voters', 'photo_path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('photo_path', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('voters', 'photo')
    ### end Alembic commands ###
